// <auto-generated />
using JO_UNI_Guide.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JO_UNI_Guide.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JO_UNI_Guide.Models.Course", b =>
                {
                    b.Property<int>("Course_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Course_ID"));

                    b.Property<string>("Course_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Department_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Department_ID1")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Course_ID");

                    b.HasIndex("Department_ID1");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("JO_UNI_Guide.Models.Department", b =>
                {
                    b.Property<int>("Department_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Department_ID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Faculty_ID")
                        .HasColumnType("integer");

                    b.HasKey("Department_ID");

                    b.HasIndex("Faculty_ID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("JO_UNI_Guide.Models.Faculty", b =>
                {
                    b.Property<int>("Faculty_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Faculty_ID"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Faculty_Dean")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("University_ID")
                        .HasColumnType("integer");

                    b.HasKey("Faculty_ID");

                    b.HasIndex("University_ID");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("JO_UNI_Guide.Models.University", b =>
                {
                    b.Property<int>("University_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("University_ID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rank_QS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("University_ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("JO_UNI_Guide.Models.Course", b =>
                {
                    b.HasOne("JO_UNI_Guide.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("Department_ID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("JO_UNI_Guide.Models.Department", b =>
                {
                    b.HasOne("JO_UNI_Guide.Models.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("Faculty_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("JO_UNI_Guide.Models.Faculty", b =>
                {
                    b.HasOne("JO_UNI_Guide.Models.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("University_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("JO_UNI_Guide.Models.Department", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("JO_UNI_Guide.Models.Faculty", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("JO_UNI_Guide.Models.University", b =>
                {
                    b.Navigation("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
